[build]
  command = "npm ci --include=dev && ./node_modules/.bin/tailwindcss --version && hugo --gc --minify -b $URL && npx --yes pagefind --source 'public'"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.150.0"
  HUGO_EXTENDED = "true"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "22"
  TZ = "Asia/Tokyo"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && npx pagefind --source 'public'"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
